namespace Classes.DestinyApi
{
    public class Manifest
    {
        public string version { get; set; }
        public string mobileAssetContentPath { get; set; }
        public Mobilegearassetdatabas[] mobileGearAssetDataBases { get; set; }
        public Mobileworldcontentpaths mobileWorldContentPaths { get; set; }
        public Jsonworldcontentpaths jsonWorldContentPaths { get; set; }
        public Jsonworldcomponentcontentpaths jsonWorldComponentContentPaths { get; set; }
        public string mobileClanBannerDatabasePath { get; set; }
        public Mobilegearcdn mobileGearCDN { get; set; }
        public object[] iconImagePyramidInfo { get; set; }
    }

    public class Mobileworldcontentpaths
    {
        public string en { get; set; }
        public string fr { get; set; }
        public string es { get; set; }
        public string esmx { get; set; }
        public string de { get; set; }
        public string it { get; set; }
        public string ja { get; set; }
        public string ptbr { get; set; }
        public string ru { get; set; }
        public string pl { get; set; }
        public string ko { get; set; }
        public string zhcht { get; set; }
        public string zhchs { get; set; }
    }

    public class Jsonworldcontentpaths
    {
        public string en { get; set; }
        public string fr { get; set; }
        public string es { get; set; }
        public string esmx { get; set; }
        public string de { get; set; }
        public string it { get; set; }
        public string ja { get; set; }
        public string ptbr { get; set; }
        public string ru { get; set; }
        public string pl { get; set; }
        public string ko { get; set; }
        public string zhcht { get; set; }
        public string zhchs { get; set; }
    }

    public class Jsonworldcomponentcontentpaths
    {
        public En en { get; set; }
        public Fr fr { get; set; }
        public Es es { get; set; }
        public EsMx esmx { get; set; }
        public De de { get; set; }
        public It it { get; set; }
        public Ja ja { get; set; }
        public PtBr ptbr { get; set; }
        public Ru ru { get; set; }
        public Pl pl { get; set; }
        public Ko ko { get; set; }
        public ZhCht zhcht { get; set; }
        public ZhChs zhchs { get; set; }
    }

    public class En
    {
        public string DestinyArtDyeChannelDefinition { get; set; }
        public string DestinyArtDyeReferenceDefinition { get; set; }
        public string DestinyPlaceDefinition { get; set; }
        public string DestinyActivityDefinition { get; set; }
        public string DestinyActivityTypeDefinition { get; set; }
        public string DestinyClassDefinition { get; set; }
        public string DestinyGenderDefinition { get; set; }
        public string DestinyInventoryBucketDefinition { get; set; }
        public string DestinyRaceDefinition { get; set; }
        public string DestinyUnlockDefinition { get; set; }
        public string DestinyStatGroupDefinition { get; set; }
        public string DestinyProgressionMappingDefinition { get; set; }
        public string DestinyFactionDefinition { get; set; }
        public string DestinyVendorGroupDefinition { get; set; }
        public string DestinyRewardSourceDefinition { get; set; }
        public string DestinyUnlockValueDefinition { get; set; }
        public string DestinyRewardMappingDefinition { get; set; }
        public string DestinyItemCategoryDefinition { get; set; }
        public string DestinyDamageTypeDefinition { get; set; }
        public string DestinyActivityModeDefinition { get; set; }
        public string DestinyMedalTierDefinition { get; set; }
        public string DestinyAchievementDefinition { get; set; }
        public string DestinyActivityDifficultyTierCollectionDefinition { get; set; }
        public string DestinyActivityFamilyDefinition { get; set; }
        public string DestinyActivityGraphDefinition { get; set; }
        public string DestinyActivityInteractableDefinition { get; set; }
        public string DestinyActivityLoadoutRestrictionDefinition { get; set; }
        public string DestinyActivitySelectableSkullCollectionDefinition { get; set; }
        public string DestinyActivitySelectableSkullExclusionGroupDefinition { get; set; }
        public string DestinyActivitySkullCategoryDefinition { get; set; }
        public string DestinyActivitySkullCollectionDefinition { get; set; }
        public string DestinyActivitySkullSubcategoryDefinition { get; set; }
        public string DestinyBondDefinition { get; set; }
        public string DestinyCharacterCustomizationCategoryDefinition { get; set; }
        public string DestinyCharacterCustomizationOptionDefinition { get; set; }
        public string DestinyCollectibleDefinition { get; set; }
        public string DestinyDestinationDefinition { get; set; }
        public string DestinyEntitlementOfferDefinition { get; set; }
        public string DestinyEquipableItemSetDefinition { get; set; }
        public string DestinyEquipmentSlotDefinition { get; set; }
        public string DestinyEventCardDefinition { get; set; }
        public string DestinyFireteamFinderActivityGraphDefinition { get; set; }
        public string DestinyFireteamFinderActivitySetDefinition { get; set; }
        public string DestinyFireteamFinderLabelDefinition { get; set; }
        public string DestinyFireteamFinderLabelGroupDefinition { get; set; }
        public string DestinyFireteamFinderOptionDefinition { get; set; }
        public string DestinyFireteamFinderOptionGroupDefinition { get; set; }
        public string DestinyStatDefinition { get; set; }
        public string DestinyInventoryItemDefinition { get; set; }
        public string DestinyInventoryItemLiteDefinition { get; set; }
        public string DestinyItemFilterDefinition { get; set; }
        public string DestinyItemTierTypeDefinition { get; set; }
        public string DestinyLoadoutColorDefinition { get; set; }
        public string DestinyLoadoutIconDefinition { get; set; }
        public string DestinyLoadoutNameDefinition { get; set; }
        public string DestinyLocationDefinition { get; set; }
        public string DestinyLoreDefinition { get; set; }
        public string DestinyMaterialRequirementSetDefinition { get; set; }
        public string DestinyMetricDefinition { get; set; }
        public string DestinyObjectiveDefinition { get; set; }
        public string DestinySandboxPerkDefinition { get; set; }
        public string DestinyPlatformBucketMappingDefinition { get; set; }
        public string DestinyPlugSetDefinition { get; set; }
        public string DestinyPowerCapDefinition { get; set; }
        public string DestinyPresentationNodeDefinition { get; set; }
        public string DestinyProgressionDefinition { get; set; }
        public string DestinyProgressionLevelRequirementDefinition { get; set; }
        public string DestinyRecordDefinition { get; set; }
        public string DestinyRewardAdjusterPointerDefinition { get; set; }
        public string DestinyRewardAdjusterProgressionMapDefinition { get; set; }
        public string DestinyRewardItemListDefinition { get; set; }
        public string DestinySackRewardItemListDefinition { get; set; }
        public string DestinySandboxPatternDefinition { get; set; }
        public string DestinySeasonDefinition { get; set; }
        public string DestinySeasonPassDefinition { get; set; }
        public string DestinySocialCommendationDefinition { get; set; }
        public string DestinySocketCategoryDefinition { get; set; }
        public string DestinySocketTypeDefinition { get; set; }
        public string DestinyTraitDefinition { get; set; }
        public string DestinyUnlockCountMappingDefinition { get; set; }
        public string DestinyUnlockEventDefinition { get; set; }
        public string DestinyUnlockExpressionMappingDefinition { get; set; }
        public string DestinyVendorDefinition { get; set; }
        public string DestinyMilestoneDefinition { get; set; }
        public string DestinyActivityModifierDefinition { get; set; }
        public string DestinyReportReasonCategoryDefinition { get; set; }
        public string DestinyArtifactDefinition { get; set; }
        public string DestinyBreakerTypeDefinition { get; set; }
        public string DestinyChecklistDefinition { get; set; }
        public string DestinyEnergyTypeDefinition { get; set; }
        public string DestinySocialCommendationNodeDefinition { get; set; }
        public string DestinyGuardianRankDefinition { get; set; }
        public string DestinyGuardianRankConstantsDefinition { get; set; }
        public string DestinyLoadoutConstantsDefinition { get; set; }
        public string DestinyFireteamFinderConstantsDefinition { get; set; }
        public string DestinyGlobalConstantsDefinition { get; set; }
        public string DestinyInventoryItemConstantsDefinition { get; set; }
    }

    public class Fr
    {
        public string DestinyArtDyeChannelDefinition { get; set; }
        public string DestinyArtDyeReferenceDefinition { get; set; }
        public string DestinyPlaceDefinition { get; set; }
        public string DestinyActivityDefinition { get; set; }
        public string DestinyActivityTypeDefinition { get; set; }
        public string DestinyClassDefinition { get; set; }
        public string DestinyGenderDefinition { get; set; }
        public string DestinyInventoryBucketDefinition { get; set; }
        public string DestinyRaceDefinition { get; set; }
        public string DestinyUnlockDefinition { get; set; }
        public string DestinyStatGroupDefinition { get; set; }
        public string DestinyProgressionMappingDefinition { get; set; }
        public string DestinyFactionDefinition { get; set; }
        public string DestinyVendorGroupDefinition { get; set; }
        public string DestinyRewardSourceDefinition { get; set; }
        public string DestinyUnlockValueDefinition { get; set; }
        public string DestinyRewardMappingDefinition { get; set; }
        public string DestinyItemCategoryDefinition { get; set; }
        public string DestinyDamageTypeDefinition { get; set; }
        public string DestinyActivityModeDefinition { get; set; }
        public string DestinyMedalTierDefinition { get; set; }
        public string DestinyAchievementDefinition { get; set; }
        public string DestinyActivityDifficultyTierCollectionDefinition { get; set; }
        public string DestinyActivityFamilyDefinition { get; set; }
        public string DestinyActivityGraphDefinition { get; set; }
        public string DestinyActivityInteractableDefinition { get; set; }
        public string DestinyActivityLoadoutRestrictionDefinition { get; set; }
        public string DestinyActivitySelectableSkullCollectionDefinition { get; set; }
        public string DestinyActivitySelectableSkullExclusionGroupDefinition { get; set; }
        public string DestinyActivitySkullCategoryDefinition { get; set; }
        public string DestinyActivitySkullCollectionDefinition { get; set; }
        public string DestinyActivitySkullSubcategoryDefinition { get; set; }
        public string DestinyBondDefinition { get; set; }
        public string DestinyCharacterCustomizationCategoryDefinition { get; set; }
        public string DestinyCharacterCustomizationOptionDefinition { get; set; }
        public string DestinyCollectibleDefinition { get; set; }
        public string DestinyDestinationDefinition { get; set; }
        public string DestinyEntitlementOfferDefinition { get; set; }
        public string DestinyEquipableItemSetDefinition { get; set; }
        public string DestinyEquipmentSlotDefinition { get; set; }
        public string DestinyEventCardDefinition { get; set; }
        public string DestinyFireteamFinderActivityGraphDefinition { get; set; }
        public string DestinyFireteamFinderActivitySetDefinition { get; set; }
        public string DestinyFireteamFinderLabelDefinition { get; set; }
        public string DestinyFireteamFinderLabelGroupDefinition { get; set; }
        public string DestinyFireteamFinderOptionDefinition { get; set; }
        public string DestinyFireteamFinderOptionGroupDefinition { get; set; }
        public string DestinyStatDefinition { get; set; }
        public string DestinyInventoryItemDefinition { get; set; }
        public string DestinyInventoryItemLiteDefinition { get; set; }
        public string DestinyItemFilterDefinition { get; set; }
        public string DestinyItemTierTypeDefinition { get; set; }
        public string DestinyLoadoutColorDefinition { get; set; }
        public string DestinyLoadoutIconDefinition { get; set; }
        public string DestinyLoadoutNameDefinition { get; set; }
        public string DestinyLocationDefinition { get; set; }
        public string DestinyLoreDefinition { get; set; }
        public string DestinyMaterialRequirementSetDefinition { get; set; }
        public string DestinyMetricDefinition { get; set; }
        public string DestinyObjectiveDefinition { get; set; }
        public string DestinySandboxPerkDefinition { get; set; }
        public string DestinyPlatformBucketMappingDefinition { get; set; }
        public string DestinyPlugSetDefinition { get; set; }
        public string DestinyPowerCapDefinition { get; set; }
        public string DestinyPresentationNodeDefinition { get; set; }
        public string DestinyProgressionDefinition { get; set; }
        public string DestinyProgressionLevelRequirementDefinition { get; set; }
        public string DestinyRecordDefinition { get; set; }
        public string DestinyRewardAdjusterPointerDefinition { get; set; }
        public string DestinyRewardAdjusterProgressionMapDefinition { get; set; }
        public string DestinyRewardItemListDefinition { get; set; }
        public string DestinySackRewardItemListDefinition { get; set; }
        public string DestinySandboxPatternDefinition { get; set; }
        public string DestinySeasonDefinition { get; set; }
        public string DestinySeasonPassDefinition { get; set; }
        public string DestinySocialCommendationDefinition { get; set; }
        public string DestinySocketCategoryDefinition { get; set; }
        public string DestinySocketTypeDefinition { get; set; }
        public string DestinyTraitDefinition { get; set; }
        public string DestinyUnlockCountMappingDefinition { get; set; }
        public string DestinyUnlockEventDefinition { get; set; }
        public string DestinyUnlockExpressionMappingDefinition { get; set; }
        public string DestinyVendorDefinition { get; set; }
        public string DestinyMilestoneDefinition { get; set; }
        public string DestinyActivityModifierDefinition { get; set; }
        public string DestinyReportReasonCategoryDefinition { get; set; }
        public string DestinyArtifactDefinition { get; set; }
        public string DestinyBreakerTypeDefinition { get; set; }
        public string DestinyChecklistDefinition { get; set; }
        public string DestinyEnergyTypeDefinition { get; set; }
        public string DestinySocialCommendationNodeDefinition { get; set; }
        public string DestinyGuardianRankDefinition { get; set; }
        public string DestinyGuardianRankConstantsDefinition { get; set; }
        public string DestinyLoadoutConstantsDefinition { get; set; }
        public string DestinyFireteamFinderConstantsDefinition { get; set; }
        public string DestinyGlobalConstantsDefinition { get; set; }
        public string DestinyInventoryItemConstantsDefinition { get; set; }
    }

    public class Es
    {
        public string DestinyArtDyeChannelDefinition { get; set; }
        public string DestinyArtDyeReferenceDefinition { get; set; }
        public string DestinyPlaceDefinition { get; set; }
        public string DestinyActivityDefinition { get; set; }
        public string DestinyActivityTypeDefinition { get; set; }
        public string DestinyClassDefinition { get; set; }
        public string DestinyGenderDefinition { get; set; }
        public string DestinyInventoryBucketDefinition { get; set; }
        public string DestinyRaceDefinition { get; set; }
        public string DestinyUnlockDefinition { get; set; }
        public string DestinyStatGroupDefinition { get; set; }
        public string DestinyProgressionMappingDefinition { get; set; }
        public string DestinyFactionDefinition { get; set; }
        public string DestinyVendorGroupDefinition { get; set; }
        public string DestinyRewardSourceDefinition { get; set; }
        public string DestinyUnlockValueDefinition { get; set; }
        public string DestinyRewardMappingDefinition { get; set; }
        public string DestinyItemCategoryDefinition { get; set; }
        public string DestinyDamageTypeDefinition { get; set; }
        public string DestinyActivityModeDefinition { get; set; }
        public string DestinyMedalTierDefinition { get; set; }
        public string DestinyAchievementDefinition { get; set; }
        public string DestinyActivityDifficultyTierCollectionDefinition { get; set; }
        public string DestinyActivityFamilyDefinition { get; set; }
        public string DestinyActivityGraphDefinition { get; set; }
        public string DestinyActivityInteractableDefinition { get; set; }
        public string DestinyActivityLoadoutRestrictionDefinition { get; set; }
        public string DestinyActivitySelectableSkullCollectionDefinition { get; set; }
        public string DestinyActivitySelectableSkullExclusionGroupDefinition { get; set; }
        public string DestinyActivitySkullCategoryDefinition { get; set; }
        public string DestinyActivitySkullCollectionDefinition { get; set; }
        public string DestinyActivitySkullSubcategoryDefinition { get; set; }
        public string DestinyBondDefinition { get; set; }
        public string DestinyCharacterCustomizationCategoryDefinition { get; set; }
        public string DestinyCharacterCustomizationOptionDefinition { get; set; }
        public string DestinyCollectibleDefinition { get; set; }
        public string DestinyDestinationDefinition { get; set; }
        public string DestinyEntitlementOfferDefinition { get; set; }
        public string DestinyEquipableItemSetDefinition { get; set; }
        public string DestinyEquipmentSlotDefinition { get; set; }
        public string DestinyEventCardDefinition { get; set; }
        public string DestinyFireteamFinderActivityGraphDefinition { get; set; }
        public string DestinyFireteamFinderActivitySetDefinition { get; set; }
        public string DestinyFireteamFinderLabelDefinition { get; set; }
        public string DestinyFireteamFinderLabelGroupDefinition { get; set; }
        public string DestinyFireteamFinderOptionDefinition { get; set; }
        public string DestinyFireteamFinderOptionGroupDefinition { get; set; }
        public string DestinyStatDefinition { get; set; }
        public string DestinyInventoryItemDefinition { get; set; }
        public string DestinyInventoryItemLiteDefinition { get; set; }
        public string DestinyItemFilterDefinition { get; set; }
        public string DestinyItemTierTypeDefinition { get; set; }
        public string DestinyLoadoutColorDefinition { get; set; }
        public string DestinyLoadoutIconDefinition { get; set; }
        public string DestinyLoadoutNameDefinition { get; set; }
        public string DestinyLocationDefinition { get; set; }
        public string DestinyLoreDefinition { get; set; }
        public string DestinyMaterialRequirementSetDefinition { get; set; }
        public string DestinyMetricDefinition { get; set; }
        public string DestinyObjectiveDefinition { get; set; }
        public string DestinySandboxPerkDefinition { get; set; }
        public string DestinyPlatformBucketMappingDefinition { get; set; }
        public string DestinyPlugSetDefinition { get; set; }
        public string DestinyPowerCapDefinition { get; set; }
        public string DestinyPresentationNodeDefinition { get; set; }
        public string DestinyProgressionDefinition { get; set; }
        public string DestinyProgressionLevelRequirementDefinition { get; set; }
        public string DestinyRecordDefinition { get; set; }
        public string DestinyRewardAdjusterPointerDefinition { get; set; }
        public string DestinyRewardAdjusterProgressionMapDefinition { get; set; }
        public string DestinyRewardItemListDefinition { get; set; }
        public string DestinySackRewardItemListDefinition { get; set; }
        public string DestinySandboxPatternDefinition { get; set; }
        public string DestinySeasonDefinition { get; set; }
        public string DestinySeasonPassDefinition { get; set; }
        public string DestinySocialCommendationDefinition { get; set; }
        public string DestinySocketCategoryDefinition { get; set; }
        public string DestinySocketTypeDefinition { get; set; }
        public string DestinyTraitDefinition { get; set; }
        public string DestinyUnlockCountMappingDefinition { get; set; }
        public string DestinyUnlockEventDefinition { get; set; }
        public string DestinyUnlockExpressionMappingDefinition { get; set; }
        public string DestinyVendorDefinition { get; set; }
        public string DestinyMilestoneDefinition { get; set; }
        public string DestinyActivityModifierDefinition { get; set; }
        public string DestinyReportReasonCategoryDefinition { get; set; }
        public string DestinyArtifactDefinition { get; set; }
        public string DestinyBreakerTypeDefinition { get; set; }
        public string DestinyChecklistDefinition { get; set; }
        public string DestinyEnergyTypeDefinition { get; set; }
        public string DestinySocialCommendationNodeDefinition { get; set; }
        public string DestinyGuardianRankDefinition { get; set; }
        public string DestinyGuardianRankConstantsDefinition { get; set; }
        public string DestinyLoadoutConstantsDefinition { get; set; }
        public string DestinyFireteamFinderConstantsDefinition { get; set; }
        public string DestinyGlobalConstantsDefinition { get; set; }
        public string DestinyInventoryItemConstantsDefinition { get; set; }
    }

    public class EsMx
    {
        public string DestinyArtDyeChannelDefinition { get; set; }
        public string DestinyArtDyeReferenceDefinition { get; set; }
        public string DestinyPlaceDefinition { get; set; }
        public string DestinyActivityDefinition { get; set; }
        public string DestinyActivityTypeDefinition { get; set; }
        public string DestinyClassDefinition { get; set; }
        public string DestinyGenderDefinition { get; set; }
        public string DestinyInventoryBucketDefinition { get; set; }
        public string DestinyRaceDefinition { get; set; }
        public string DestinyUnlockDefinition { get; set; }
        public string DestinyStatGroupDefinition { get; set; }
        public string DestinyProgressionMappingDefinition { get; set; }
        public string DestinyFactionDefinition { get; set; }
        public string DestinyVendorGroupDefinition { get; set; }
        public string DestinyRewardSourceDefinition { get; set; }
        public string DestinyUnlockValueDefinition { get; set; }
        public string DestinyRewardMappingDefinition { get; set; }
        public string DestinyItemCategoryDefinition { get; set; }
        public string DestinyDamageTypeDefinition { get; set; }
        public string DestinyActivityModeDefinition { get; set; }
        public string DestinyMedalTierDefinition { get; set; }
        public string DestinyAchievementDefinition { get; set; }
        public string DestinyActivityDifficultyTierCollectionDefinition { get; set; }
        public string DestinyActivityFamilyDefinition { get; set; }
        public string DestinyActivityGraphDefinition { get; set; }
        public string DestinyActivityInteractableDefinition { get; set; }
        public string DestinyActivityLoadoutRestrictionDefinition { get; set; }
        public string DestinyActivitySelectableSkullCollectionDefinition { get; set; }
        public string DestinyActivitySelectableSkullExclusionGroupDefinition { get; set; }
        public string DestinyActivitySkullCategoryDefinition { get; set; }
        public string DestinyActivitySkullCollectionDefinition { get; set; }
        public string DestinyActivitySkullSubcategoryDefinition { get; set; }
        public string DestinyBondDefinition { get; set; }
        public string DestinyCharacterCustomizationCategoryDefinition { get; set; }
        public string DestinyCharacterCustomizationOptionDefinition { get; set; }
        public string DestinyCollectibleDefinition { get; set; }
        public string DestinyDestinationDefinition { get; set; }
        public string DestinyEntitlementOfferDefinition { get; set; }
        public string DestinyEquipableItemSetDefinition { get; set; }
        public string DestinyEquipmentSlotDefinition { get; set; }
        public string DestinyEventCardDefinition { get; set; }
        public string DestinyFireteamFinderActivityGraphDefinition { get; set; }
        public string DestinyFireteamFinderActivitySetDefinition { get; set; }
        public string DestinyFireteamFinderLabelDefinition { get; set; }
        public string DestinyFireteamFinderLabelGroupDefinition { get; set; }
        public string DestinyFireteamFinderOptionDefinition { get; set; }
        public string DestinyFireteamFinderOptionGroupDefinition { get; set; }
        public string DestinyStatDefinition { get; set; }
        public string DestinyInventoryItemDefinition { get; set; }
        public string DestinyInventoryItemLiteDefinition { get; set; }
        public string DestinyItemFilterDefinition { get; set; }
        public string DestinyItemTierTypeDefinition { get; set; }
        public string DestinyLoadoutColorDefinition { get; set; }
        public string DestinyLoadoutIconDefinition { get; set; }
        public string DestinyLoadoutNameDefinition { get; set; }
        public string DestinyLocationDefinition { get; set; }
        public string DestinyLoreDefinition { get; set; }
        public string DestinyMaterialRequirementSetDefinition { get; set; }
        public string DestinyMetricDefinition { get; set; }
        public string DestinyObjectiveDefinition { get; set; }
        public string DestinySandboxPerkDefinition { get; set; }
        public string DestinyPlatformBucketMappingDefinition { get; set; }
        public string DestinyPlugSetDefinition { get; set; }
        public string DestinyPowerCapDefinition { get; set; }
        public string DestinyPresentationNodeDefinition { get; set; }
        public string DestinyProgressionDefinition { get; set; }
        public string DestinyProgressionLevelRequirementDefinition { get; set; }
        public string DestinyRecordDefinition { get; set; }
        public string DestinyRewardAdjusterPointerDefinition { get; set; }
        public string DestinyRewardAdjusterProgressionMapDefinition { get; set; }
        public string DestinyRewardItemListDefinition { get; set; }
        public string DestinySackRewardItemListDefinition { get; set; }
        public string DestinySandboxPatternDefinition { get; set; }
        public string DestinySeasonDefinition { get; set; }
        public string DestinySeasonPassDefinition { get; set; }
        public string DestinySocialCommendationDefinition { get; set; }
        public string DestinySocketCategoryDefinition { get; set; }
        public string DestinySocketTypeDefinition { get; set; }
        public string DestinyTraitDefinition { get; set; }
        public string DestinyUnlockCountMappingDefinition { get; set; }
        public string DestinyUnlockEventDefinition { get; set; }
        public string DestinyUnlockExpressionMappingDefinition { get; set; }
        public string DestinyVendorDefinition { get; set; }
        public string DestinyMilestoneDefinition { get; set; }
        public string DestinyActivityModifierDefinition { get; set; }
        public string DestinyReportReasonCategoryDefinition { get; set; }
        public string DestinyArtifactDefinition { get; set; }
        public string DestinyBreakerTypeDefinition { get; set; }
        public string DestinyChecklistDefinition { get; set; }
        public string DestinyEnergyTypeDefinition { get; set; }
        public string DestinySocialCommendationNodeDefinition { get; set; }
        public string DestinyGuardianRankDefinition { get; set; }
        public string DestinyGuardianRankConstantsDefinition { get; set; }
        public string DestinyLoadoutConstantsDefinition { get; set; }
        public string DestinyFireteamFinderConstantsDefinition { get; set; }
        public string DestinyGlobalConstantsDefinition { get; set; }
        public string DestinyInventoryItemConstantsDefinition { get; set; }
    }

    public class De
    {
        public string DestinyArtDyeChannelDefinition { get; set; }
        public string DestinyArtDyeReferenceDefinition { get; set; }
        public string DestinyPlaceDefinition { get; set; }
        public string DestinyActivityDefinition { get; set; }
        public string DestinyActivityTypeDefinition { get; set; }
        public string DestinyClassDefinition { get; set; }
        public string DestinyGenderDefinition { get; set; }
        public string DestinyInventoryBucketDefinition { get; set; }
        public string DestinyRaceDefinition { get; set; }
        public string DestinyUnlockDefinition { get; set; }
        public string DestinyStatGroupDefinition { get; set; }
        public string DestinyProgressionMappingDefinition { get; set; }
        public string DestinyFactionDefinition { get; set; }
        public string DestinyVendorGroupDefinition { get; set; }
        public string DestinyRewardSourceDefinition { get; set; }
        public string DestinyUnlockValueDefinition { get; set; }
        public string DestinyRewardMappingDefinition { get; set; }
        public string DestinyItemCategoryDefinition { get; set; }
        public string DestinyDamageTypeDefinition { get; set; }
        public string DestinyActivityModeDefinition { get; set; }
        public string DestinyMedalTierDefinition { get; set; }
        public string DestinyAchievementDefinition { get; set; }
        public string DestinyActivityDifficultyTierCollectionDefinition { get; set; }
        public string DestinyActivityFamilyDefinition { get; set; }
        public string DestinyActivityGraphDefinition { get; set; }
        public string DestinyActivityInteractableDefinition { get; set; }
        public string DestinyActivityLoadoutRestrictionDefinition { get; set; }
        public string DestinyActivitySelectableSkullCollectionDefinition { get; set; }
        public string DestinyActivitySelectableSkullExclusionGroupDefinition { get; set; }
        public string DestinyActivitySkullCategoryDefinition { get; set; }
        public string DestinyActivitySkullCollectionDefinition { get; set; }
        public string DestinyActivitySkullSubcategoryDefinition { get; set; }
        public string DestinyBondDefinition { get; set; }
        public string DestinyCharacterCustomizationCategoryDefinition { get; set; }
        public string DestinyCharacterCustomizationOptionDefinition { get; set; }
        public string DestinyCollectibleDefinition { get; set; }
        public string DestinyDestinationDefinition { get; set; }
        public string DestinyEntitlementOfferDefinition { get; set; }
        public string DestinyEquipableItemSetDefinition { get; set; }
        public string DestinyEquipmentSlotDefinition { get; set; }
        public string DestinyEventCardDefinition { get; set; }
        public string DestinyFireteamFinderActivityGraphDefinition { get; set; }
        public string DestinyFireteamFinderActivitySetDefinition { get; set; }
        public string DestinyFireteamFinderLabelDefinition { get; set; }
        public string DestinyFireteamFinderLabelGroupDefinition { get; set; }
        public string DestinyFireteamFinderOptionDefinition { get; set; }
        public string DestinyFireteamFinderOptionGroupDefinition { get; set; }
        public string DestinyStatDefinition { get; set; }
        public string DestinyInventoryItemDefinition { get; set; }
        public string DestinyInventoryItemLiteDefinition { get; set; }
        public string DestinyItemFilterDefinition { get; set; }
        public string DestinyItemTierTypeDefinition { get; set; }
        public string DestinyLoadoutColorDefinition { get; set; }
        public string DestinyLoadoutIconDefinition { get; set; }
        public string DestinyLoadoutNameDefinition { get; set; }
        public string DestinyLocationDefinition { get; set; }
        public string DestinyLoreDefinition { get; set; }
        public string DestinyMaterialRequirementSetDefinition { get; set; }
        public string DestinyMetricDefinition { get; set; }
        public string DestinyObjectiveDefinition { get; set; }
        public string DestinySandboxPerkDefinition { get; set; }
        public string DestinyPlatformBucketMappingDefinition { get; set; }
        public string DestinyPlugSetDefinition { get; set; }
        public string DestinyPowerCapDefinition { get; set; }
        public string DestinyPresentationNodeDefinition { get; set; }
        public string DestinyProgressionDefinition { get; set; }
        public string DestinyProgressionLevelRequirementDefinition { get; set; }
        public string DestinyRecordDefinition { get; set; }
        public string DestinyRewardAdjusterPointerDefinition { get; set; }
        public string DestinyRewardAdjusterProgressionMapDefinition { get; set; }
        public string DestinyRewardItemListDefinition { get; set; }
        public string DestinySackRewardItemListDefinition { get; set; }
        public string DestinySandboxPatternDefinition { get; set; }
        public string DestinySeasonDefinition { get; set; }
        public string DestinySeasonPassDefinition { get; set; }
        public string DestinySocialCommendationDefinition { get; set; }
        public string DestinySocketCategoryDefinition { get; set; }
        public string DestinySocketTypeDefinition { get; set; }
        public string DestinyTraitDefinition { get; set; }
        public string DestinyUnlockCountMappingDefinition { get; set; }
        public string DestinyUnlockEventDefinition { get; set; }
        public string DestinyUnlockExpressionMappingDefinition { get; set; }
        public string DestinyVendorDefinition { get; set; }
        public string DestinyMilestoneDefinition { get; set; }
        public string DestinyActivityModifierDefinition { get; set; }
        public string DestinyReportReasonCategoryDefinition { get; set; }
        public string DestinyArtifactDefinition { get; set; }
        public string DestinyBreakerTypeDefinition { get; set; }
        public string DestinyChecklistDefinition { get; set; }
        public string DestinyEnergyTypeDefinition { get; set; }
        public string DestinySocialCommendationNodeDefinition { get; set; }
        public string DestinyGuardianRankDefinition { get; set; }
        public string DestinyGuardianRankConstantsDefinition { get; set; }
        public string DestinyLoadoutConstantsDefinition { get; set; }
        public string DestinyFireteamFinderConstantsDefinition { get; set; }
        public string DestinyGlobalConstantsDefinition { get; set; }
        public string DestinyInventoryItemConstantsDefinition { get; set; }
    }

    public class It
    {
        public string DestinyArtDyeChannelDefinition { get; set; }
        public string DestinyArtDyeReferenceDefinition { get; set; }
        public string DestinyPlaceDefinition { get; set; }
        public string DestinyActivityDefinition { get; set; }
        public string DestinyActivityTypeDefinition { get; set; }
        public string DestinyClassDefinition { get; set; }
        public string DestinyGenderDefinition { get; set; }
        public string DestinyInventoryBucketDefinition { get; set; }
        public string DestinyRaceDefinition { get; set; }
        public string DestinyUnlockDefinition { get; set; }
        public string DestinyStatGroupDefinition { get; set; }
        public string DestinyProgressionMappingDefinition { get; set; }
        public string DestinyFactionDefinition { get; set; }
        public string DestinyVendorGroupDefinition { get; set; }
        public string DestinyRewardSourceDefinition { get; set; }
        public string DestinyUnlockValueDefinition { get; set; }
        public string DestinyRewardMappingDefinition { get; set; }
        public string DestinyItemCategoryDefinition { get; set; }
        public string DestinyDamageTypeDefinition { get; set; }
        public string DestinyActivityModeDefinition { get; set; }
        public string DestinyMedalTierDefinition { get; set; }
        public string DestinyAchievementDefinition { get; set; }
        public string DestinyActivityDifficultyTierCollectionDefinition { get; set; }
        public string DestinyActivityFamilyDefinition { get; set; }
        public string DestinyActivityGraphDefinition { get; set; }
        public string DestinyActivityInteractableDefinition { get; set; }
        public string DestinyActivityLoadoutRestrictionDefinition { get; set; }
        public string DestinyActivitySelectableSkullCollectionDefinition { get; set; }
        public string DestinyActivitySelectableSkullExclusionGroupDefinition { get; set; }
        public string DestinyActivitySkullCategoryDefinition { get; set; }
        public string DestinyActivitySkullCollectionDefinition { get; set; }
        public string DestinyActivitySkullSubcategoryDefinition { get; set; }
        public string DestinyBondDefinition { get; set; }
        public string DestinyCharacterCustomizationCategoryDefinition { get; set; }
        public string DestinyCharacterCustomizationOptionDefinition { get; set; }
        public string DestinyCollectibleDefinition { get; set; }
        public string DestinyDestinationDefinition { get; set; }
        public string DestinyEntitlementOfferDefinition { get; set; }
        public string DestinyEquipableItemSetDefinition { get; set; }
        public string DestinyEquipmentSlotDefinition { get; set; }
        public string DestinyEventCardDefinition { get; set; }
        public string DestinyFireteamFinderActivityGraphDefinition { get; set; }
        public string DestinyFireteamFinderActivitySetDefinition { get; set; }
        public string DestinyFireteamFinderLabelDefinition { get; set; }
        public string DestinyFireteamFinderLabelGroupDefinition { get; set; }
        public string DestinyFireteamFinderOptionDefinition { get; set; }
        public string DestinyFireteamFinderOptionGroupDefinition { get; set; }
        public string DestinyStatDefinition { get; set; }
        public string DestinyInventoryItemDefinition { get; set; }
        public string DestinyInventoryItemLiteDefinition { get; set; }
        public string DestinyItemFilterDefinition { get; set; }
        public string DestinyItemTierTypeDefinition { get; set; }
        public string DestinyLoadoutColorDefinition { get; set; }
        public string DestinyLoadoutIconDefinition { get; set; }
        public string DestinyLoadoutNameDefinition { get; set; }
        public string DestinyLocationDefinition { get; set; }
        public string DestinyLoreDefinition { get; set; }
        public string DestinyMaterialRequirementSetDefinition { get; set; }
        public string DestinyMetricDefinition { get; set; }
        public string DestinyObjectiveDefinition { get; set; }
        public string DestinySandboxPerkDefinition { get; set; }
        public string DestinyPlatformBucketMappingDefinition { get; set; }
        public string DestinyPlugSetDefinition { get; set; }
        public string DestinyPowerCapDefinition { get; set; }
        public string DestinyPresentationNodeDefinition { get; set; }
        public string DestinyProgressionDefinition { get; set; }
        public string DestinyProgressionLevelRequirementDefinition { get; set; }
        public string DestinyRecordDefinition { get; set; }
        public string DestinyRewardAdjusterPointerDefinition { get; set; }
        public string DestinyRewardAdjusterProgressionMapDefinition { get; set; }
        public string DestinyRewardItemListDefinition { get; set; }
        public string DestinySackRewardItemListDefinition { get; set; }
        public string DestinySandboxPatternDefinition { get; set; }
        public string DestinySeasonDefinition { get; set; }
        public string DestinySeasonPassDefinition { get; set; }
        public string DestinySocialCommendationDefinition { get; set; }
        public string DestinySocketCategoryDefinition { get; set; }
        public string DestinySocketTypeDefinition { get; set; }
        public string DestinyTraitDefinition { get; set; }
        public string DestinyUnlockCountMappingDefinition { get; set; }
        public string DestinyUnlockEventDefinition { get; set; }
        public string DestinyUnlockExpressionMappingDefinition { get; set; }
        public string DestinyVendorDefinition { get; set; }
        public string DestinyMilestoneDefinition { get; set; }
        public string DestinyActivityModifierDefinition { get; set; }
        public string DestinyReportReasonCategoryDefinition { get; set; }
        public string DestinyArtifactDefinition { get; set; }
        public string DestinyBreakerTypeDefinition { get; set; }
        public string DestinyChecklistDefinition { get; set; }
        public string DestinyEnergyTypeDefinition { get; set; }
        public string DestinySocialCommendationNodeDefinition { get; set; }
        public string DestinyGuardianRankDefinition { get; set; }
        public string DestinyGuardianRankConstantsDefinition { get; set; }
        public string DestinyLoadoutConstantsDefinition { get; set; }
        public string DestinyFireteamFinderConstantsDefinition { get; set; }
        public string DestinyGlobalConstantsDefinition { get; set; }
        public string DestinyInventoryItemConstantsDefinition { get; set; }
    }

    public class Ja
    {
        public string DestinyArtDyeChannelDefinition { get; set; }
        public string DestinyArtDyeReferenceDefinition { get; set; }
        public string DestinyPlaceDefinition { get; set; }
        public string DestinyActivityDefinition { get; set; }
        public string DestinyActivityTypeDefinition { get; set; }
        public string DestinyClassDefinition { get; set; }
        public string DestinyGenderDefinition { get; set; }
        public string DestinyInventoryBucketDefinition { get; set; }
        public string DestinyRaceDefinition { get; set; }
        public string DestinyUnlockDefinition { get; set; }
        public string DestinyStatGroupDefinition { get; set; }
        public string DestinyProgressionMappingDefinition { get; set; }
        public string DestinyFactionDefinition { get; set; }
        public string DestinyVendorGroupDefinition { get; set; }
        public string DestinyRewardSourceDefinition { get; set; }
        public string DestinyUnlockValueDefinition { get; set; }
        public string DestinyRewardMappingDefinition { get; set; }
        public string DestinyItemCategoryDefinition { get; set; }
        public string DestinyDamageTypeDefinition { get; set; }
        public string DestinyActivityModeDefinition { get; set; }
        public string DestinyMedalTierDefinition { get; set; }
        public string DestinyAchievementDefinition { get; set; }
        public string DestinyActivityDifficultyTierCollectionDefinition { get; set; }
        public string DestinyActivityFamilyDefinition { get; set; }
        public string DestinyActivityGraphDefinition { get; set; }
        public string DestinyActivityInteractableDefinition { get; set; }
        public string DestinyActivityLoadoutRestrictionDefinition { get; set; }
        public string DestinyActivitySelectableSkullCollectionDefinition { get; set; }
        public string DestinyActivitySelectableSkullExclusionGroupDefinition { get; set; }
        public string DestinyActivitySkullCategoryDefinition { get; set; }
        public string DestinyActivitySkullCollectionDefinition { get; set; }
        public string DestinyActivitySkullSubcategoryDefinition { get; set; }
        public string DestinyBondDefinition { get; set; }
        public string DestinyCharacterCustomizationCategoryDefinition { get; set; }
        public string DestinyCharacterCustomizationOptionDefinition { get; set; }
        public string DestinyCollectibleDefinition { get; set; }
        public string DestinyDestinationDefinition { get; set; }
        public string DestinyEntitlementOfferDefinition { get; set; }
        public string DestinyEquipableItemSetDefinition { get; set; }
        public string DestinyEquipmentSlotDefinition { get; set; }
        public string DestinyEventCardDefinition { get; set; }
        public string DestinyFireteamFinderActivityGraphDefinition { get; set; }
        public string DestinyFireteamFinderActivitySetDefinition { get; set; }
        public string DestinyFireteamFinderLabelDefinition { get; set; }
        public string DestinyFireteamFinderLabelGroupDefinition { get; set; }
        public string DestinyFireteamFinderOptionDefinition { get; set; }
        public string DestinyFireteamFinderOptionGroupDefinition { get; set; }
        public string DestinyStatDefinition { get; set; }
        public string DestinyInventoryItemDefinition { get; set; }
        public string DestinyInventoryItemLiteDefinition { get; set; }
        public string DestinyItemFilterDefinition { get; set; }
        public string DestinyItemTierTypeDefinition { get; set; }
        public string DestinyLoadoutColorDefinition { get; set; }
        public string DestinyLoadoutIconDefinition { get; set; }
        public string DestinyLoadoutNameDefinition { get; set; }
        public string DestinyLocationDefinition { get; set; }
        public string DestinyLoreDefinition { get; set; }
        public string DestinyMaterialRequirementSetDefinition { get; set; }
        public string DestinyMetricDefinition { get; set; }
        public string DestinyObjectiveDefinition { get; set; }
        public string DestinySandboxPerkDefinition { get; set; }
        public string DestinyPlatformBucketMappingDefinition { get; set; }
        public string DestinyPlugSetDefinition { get; set; }
        public string DestinyPowerCapDefinition { get; set; }
        public string DestinyPresentationNodeDefinition { get; set; }
        public string DestinyProgressionDefinition { get; set; }
        public string DestinyProgressionLevelRequirementDefinition { get; set; }
        public string DestinyRecordDefinition { get; set; }
        public string DestinyRewardAdjusterPointerDefinition { get; set; }
        public string DestinyRewardAdjusterProgressionMapDefinition { get; set; }
        public string DestinyRewardItemListDefinition { get; set; }
        public string DestinySackRewardItemListDefinition { get; set; }
        public string DestinySandboxPatternDefinition { get; set; }
        public string DestinySeasonDefinition { get; set; }
        public string DestinySeasonPassDefinition { get; set; }
        public string DestinySocialCommendationDefinition { get; set; }
        public string DestinySocketCategoryDefinition { get; set; }
        public string DestinySocketTypeDefinition { get; set; }
        public string DestinyTraitDefinition { get; set; }
        public string DestinyUnlockCountMappingDefinition { get; set; }
        public string DestinyUnlockEventDefinition { get; set; }
        public string DestinyUnlockExpressionMappingDefinition { get; set; }
        public string DestinyVendorDefinition { get; set; }
        public string DestinyMilestoneDefinition { get; set; }
        public string DestinyActivityModifierDefinition { get; set; }
        public string DestinyReportReasonCategoryDefinition { get; set; }
        public string DestinyArtifactDefinition { get; set; }
        public string DestinyBreakerTypeDefinition { get; set; }
        public string DestinyChecklistDefinition { get; set; }
        public string DestinyEnergyTypeDefinition { get; set; }
        public string DestinySocialCommendationNodeDefinition { get; set; }
        public string DestinyGuardianRankDefinition { get; set; }
        public string DestinyGuardianRankConstantsDefinition { get; set; }
        public string DestinyLoadoutConstantsDefinition { get; set; }
        public string DestinyFireteamFinderConstantsDefinition { get; set; }
        public string DestinyGlobalConstantsDefinition { get; set; }
        public string DestinyInventoryItemConstantsDefinition { get; set; }
    }

    public class PtBr
    {
        public string DestinyArtDyeChannelDefinition { get; set; }
        public string DestinyArtDyeReferenceDefinition { get; set; }
        public string DestinyPlaceDefinition { get; set; }
        public string DestinyActivityDefinition { get; set; }
        public string DestinyActivityTypeDefinition { get; set; }
        public string DestinyClassDefinition { get; set; }
        public string DestinyGenderDefinition { get; set; }
        public string DestinyInventoryBucketDefinition { get; set; }
        public string DestinyRaceDefinition { get; set; }
        public string DestinyUnlockDefinition { get; set; }
        public string DestinyStatGroupDefinition { get; set; }
        public string DestinyProgressionMappingDefinition { get; set; }
        public string DestinyFactionDefinition { get; set; }
        public string DestinyVendorGroupDefinition { get; set; }
        public string DestinyRewardSourceDefinition { get; set; }
        public string DestinyUnlockValueDefinition { get; set; }
        public string DestinyRewardMappingDefinition { get; set; }
        public string DestinyItemCategoryDefinition { get; set; }
        public string DestinyDamageTypeDefinition { get; set; }
        public string DestinyActivityModeDefinition { get; set; }
        public string DestinyMedalTierDefinition { get; set; }
        public string DestinyAchievementDefinition { get; set; }
        public string DestinyActivityDifficultyTierCollectionDefinition { get; set; }
        public string DestinyActivityFamilyDefinition { get; set; }
        public string DestinyActivityGraphDefinition { get; set; }
        public string DestinyActivityInteractableDefinition { get; set; }
        public string DestinyActivityLoadoutRestrictionDefinition { get; set; }
        public string DestinyActivitySelectableSkullCollectionDefinition { get; set; }
        public string DestinyActivitySelectableSkullExclusionGroupDefinition { get; set; }
        public string DestinyActivitySkullCategoryDefinition { get; set; }
        public string DestinyActivitySkullCollectionDefinition { get; set; }
        public string DestinyActivitySkullSubcategoryDefinition { get; set; }
        public string DestinyBondDefinition { get; set; }
        public string DestinyCharacterCustomizationCategoryDefinition { get; set; }
        public string DestinyCharacterCustomizationOptionDefinition { get; set; }
        public string DestinyCollectibleDefinition { get; set; }
        public string DestinyDestinationDefinition { get; set; }
        public string DestinyEntitlementOfferDefinition { get; set; }
        public string DestinyEquipableItemSetDefinition { get; set; }
        public string DestinyEquipmentSlotDefinition { get; set; }
        public string DestinyEventCardDefinition { get; set; }
        public string DestinyFireteamFinderActivityGraphDefinition { get; set; }
        public string DestinyFireteamFinderActivitySetDefinition { get; set; }
        public string DestinyFireteamFinderLabelDefinition { get; set; }
        public string DestinyFireteamFinderLabelGroupDefinition { get; set; }
        public string DestinyFireteamFinderOptionDefinition { get; set; }
        public string DestinyFireteamFinderOptionGroupDefinition { get; set; }
        public string DestinyStatDefinition { get; set; }
        public string DestinyInventoryItemDefinition { get; set; }
        public string DestinyInventoryItemLiteDefinition { get; set; }
        public string DestinyItemFilterDefinition { get; set; }
        public string DestinyItemTierTypeDefinition { get; set; }
        public string DestinyLoadoutColorDefinition { get; set; }
        public string DestinyLoadoutIconDefinition { get; set; }
        public string DestinyLoadoutNameDefinition { get; set; }
        public string DestinyLocationDefinition { get; set; }
        public string DestinyLoreDefinition { get; set; }
        public string DestinyMaterialRequirementSetDefinition { get; set; }
        public string DestinyMetricDefinition { get; set; }
        public string DestinyObjectiveDefinition { get; set; }
        public string DestinySandboxPerkDefinition { get; set; }
        public string DestinyPlatformBucketMappingDefinition { get; set; }
        public string DestinyPlugSetDefinition { get; set; }
        public string DestinyPowerCapDefinition { get; set; }
        public string DestinyPresentationNodeDefinition { get; set; }
        public string DestinyProgressionDefinition { get; set; }
        public string DestinyProgressionLevelRequirementDefinition { get; set; }
        public string DestinyRecordDefinition { get; set; }
        public string DestinyRewardAdjusterPointerDefinition { get; set; }
        public string DestinyRewardAdjusterProgressionMapDefinition { get; set; }
        public string DestinyRewardItemListDefinition { get; set; }
        public string DestinySackRewardItemListDefinition { get; set; }
        public string DestinySandboxPatternDefinition { get; set; }
        public string DestinySeasonDefinition { get; set; }
        public string DestinySeasonPassDefinition { get; set; }
        public string DestinySocialCommendationDefinition { get; set; }
        public string DestinySocketCategoryDefinition { get; set; }
        public string DestinySocketTypeDefinition { get; set; }
        public string DestinyTraitDefinition { get; set; }
        public string DestinyUnlockCountMappingDefinition { get; set; }
        public string DestinyUnlockEventDefinition { get; set; }
        public string DestinyUnlockExpressionMappingDefinition { get; set; }
        public string DestinyVendorDefinition { get; set; }
        public string DestinyMilestoneDefinition { get; set; }
        public string DestinyActivityModifierDefinition { get; set; }
        public string DestinyReportReasonCategoryDefinition { get; set; }
        public string DestinyArtifactDefinition { get; set; }
        public string DestinyBreakerTypeDefinition { get; set; }
        public string DestinyChecklistDefinition { get; set; }
        public string DestinyEnergyTypeDefinition { get; set; }
        public string DestinySocialCommendationNodeDefinition { get; set; }
        public string DestinyGuardianRankDefinition { get; set; }
        public string DestinyGuardianRankConstantsDefinition { get; set; }
        public string DestinyLoadoutConstantsDefinition { get; set; }
        public string DestinyFireteamFinderConstantsDefinition { get; set; }
        public string DestinyGlobalConstantsDefinition { get; set; }
        public string DestinyInventoryItemConstantsDefinition { get; set; }
    }

    public class Ru
    {
        public string DestinyArtDyeChannelDefinition { get; set; }
        public string DestinyArtDyeReferenceDefinition { get; set; }
        public string DestinyPlaceDefinition { get; set; }
        public string DestinyActivityDefinition { get; set; }
        public string DestinyActivityTypeDefinition { get; set; }
        public string DestinyClassDefinition { get; set; }
        public string DestinyGenderDefinition { get; set; }
        public string DestinyInventoryBucketDefinition { get; set; }
        public string DestinyRaceDefinition { get; set; }
        public string DestinyUnlockDefinition { get; set; }
        public string DestinyStatGroupDefinition { get; set; }
        public string DestinyProgressionMappingDefinition { get; set; }
        public string DestinyFactionDefinition { get; set; }
        public string DestinyVendorGroupDefinition { get; set; }
        public string DestinyRewardSourceDefinition { get; set; }
        public string DestinyUnlockValueDefinition { get; set; }
        public string DestinyRewardMappingDefinition { get; set; }
        public string DestinyItemCategoryDefinition { get; set; }
        public string DestinyDamageTypeDefinition { get; set; }
        public string DestinyActivityModeDefinition { get; set; }
        public string DestinyMedalTierDefinition { get; set; }
        public string DestinyAchievementDefinition { get; set; }
        public string DestinyActivityDifficultyTierCollectionDefinition { get; set; }
        public string DestinyActivityFamilyDefinition { get; set; }
        public string DestinyActivityGraphDefinition { get; set; }
        public string DestinyActivityInteractableDefinition { get; set; }
        public string DestinyActivityLoadoutRestrictionDefinition { get; set; }
        public string DestinyActivitySelectableSkullCollectionDefinition { get; set; }
        public string DestinyActivitySelectableSkullExclusionGroupDefinition { get; set; }
        public string DestinyActivitySkullCategoryDefinition { get; set; }
        public string DestinyActivitySkullCollectionDefinition { get; set; }
        public string DestinyActivitySkullSubcategoryDefinition { get; set; }
        public string DestinyBondDefinition { get; set; }
        public string DestinyCharacterCustomizationCategoryDefinition { get; set; }
        public string DestinyCharacterCustomizationOptionDefinition { get; set; }
        public string DestinyCollectibleDefinition { get; set; }
        public string DestinyDestinationDefinition { get; set; }
        public string DestinyEntitlementOfferDefinition { get; set; }
        public string DestinyEquipableItemSetDefinition { get; set; }
        public string DestinyEquipmentSlotDefinition { get; set; }
        public string DestinyEventCardDefinition { get; set; }
        public string DestinyFireteamFinderActivityGraphDefinition { get; set; }
        public string DestinyFireteamFinderActivitySetDefinition { get; set; }
        public string DestinyFireteamFinderLabelDefinition { get; set; }
        public string DestinyFireteamFinderLabelGroupDefinition { get; set; }
        public string DestinyFireteamFinderOptionDefinition { get; set; }
        public string DestinyFireteamFinderOptionGroupDefinition { get; set; }
        public string DestinyStatDefinition { get; set; }
        public string DestinyInventoryItemDefinition { get; set; }
        public string DestinyInventoryItemLiteDefinition { get; set; }
        public string DestinyItemFilterDefinition { get; set; }
        public string DestinyItemTierTypeDefinition { get; set; }
        public string DestinyLoadoutColorDefinition { get; set; }
        public string DestinyLoadoutIconDefinition { get; set; }
        public string DestinyLoadoutNameDefinition { get; set; }
        public string DestinyLocationDefinition { get; set; }
        public string DestinyLoreDefinition { get; set; }
        public string DestinyMaterialRequirementSetDefinition { get; set; }
        public string DestinyMetricDefinition { get; set; }
        public string DestinyObjectiveDefinition { get; set; }
        public string DestinySandboxPerkDefinition { get; set; }
        public string DestinyPlatformBucketMappingDefinition { get; set; }
        public string DestinyPlugSetDefinition { get; set; }
        public string DestinyPowerCapDefinition { get; set; }
        public string DestinyPresentationNodeDefinition { get; set; }
        public string DestinyProgressionDefinition { get; set; }
        public string DestinyProgressionLevelRequirementDefinition { get; set; }
        public string DestinyRecordDefinition { get; set; }
        public string DestinyRewardAdjusterPointerDefinition { get; set; }
        public string DestinyRewardAdjusterProgressionMapDefinition { get; set; }
        public string DestinyRewardItemListDefinition { get; set; }
        public string DestinySackRewardItemListDefinition { get; set; }
        public string DestinySandboxPatternDefinition { get; set; }
        public string DestinySeasonDefinition { get; set; }
        public string DestinySeasonPassDefinition { get; set; }
        public string DestinySocialCommendationDefinition { get; set; }
        public string DestinySocketCategoryDefinition { get; set; }
        public string DestinySocketTypeDefinition { get; set; }
        public string DestinyTraitDefinition { get; set; }
        public string DestinyUnlockCountMappingDefinition { get; set; }
        public string DestinyUnlockEventDefinition { get; set; }
        public string DestinyUnlockExpressionMappingDefinition { get; set; }
        public string DestinyVendorDefinition { get; set; }
        public string DestinyMilestoneDefinition { get; set; }
        public string DestinyActivityModifierDefinition { get; set; }
        public string DestinyReportReasonCategoryDefinition { get; set; }
        public string DestinyArtifactDefinition { get; set; }
        public string DestinyBreakerTypeDefinition { get; set; }
        public string DestinyChecklistDefinition { get; set; }
        public string DestinyEnergyTypeDefinition { get; set; }
        public string DestinySocialCommendationNodeDefinition { get; set; }
        public string DestinyGuardianRankDefinition { get; set; }
        public string DestinyGuardianRankConstantsDefinition { get; set; }
        public string DestinyLoadoutConstantsDefinition { get; set; }
        public string DestinyFireteamFinderConstantsDefinition { get; set; }
        public string DestinyGlobalConstantsDefinition { get; set; }
        public string DestinyInventoryItemConstantsDefinition { get; set; }
    }

    public class Pl
    {
        public string DestinyArtDyeChannelDefinition { get; set; }
        public string DestinyArtDyeReferenceDefinition { get; set; }
        public string DestinyPlaceDefinition { get; set; }
        public string DestinyActivityDefinition { get; set; }
        public string DestinyActivityTypeDefinition { get; set; }
        public string DestinyClassDefinition { get; set; }
        public string DestinyGenderDefinition { get; set; }
        public string DestinyInventoryBucketDefinition { get; set; }
        public string DestinyRaceDefinition { get; set; }
        public string DestinyUnlockDefinition { get; set; }
        public string DestinyStatGroupDefinition { get; set; }
        public string DestinyProgressionMappingDefinition { get; set; }
        public string DestinyFactionDefinition { get; set; }
        public string DestinyVendorGroupDefinition { get; set; }
        public string DestinyRewardSourceDefinition { get; set; }
        public string DestinyUnlockValueDefinition { get; set; }
        public string DestinyRewardMappingDefinition { get; set; }
        public string DestinyItemCategoryDefinition { get; set; }
        public string DestinyDamageTypeDefinition { get; set; }
        public string DestinyActivityModeDefinition { get; set; }
        public string DestinyMedalTierDefinition { get; set; }
        public string DestinyAchievementDefinition { get; set; }
        public string DestinyActivityDifficultyTierCollectionDefinition { get; set; }
        public string DestinyActivityFamilyDefinition { get; set; }
        public string DestinyActivityGraphDefinition { get; set; }
        public string DestinyActivityInteractableDefinition { get; set; }
        public string DestinyActivityLoadoutRestrictionDefinition { get; set; }
        public string DestinyActivitySelectableSkullCollectionDefinition { get; set; }
        public string DestinyActivitySelectableSkullExclusionGroupDefinition { get; set; }
        public string DestinyActivitySkullCategoryDefinition { get; set; }
        public string DestinyActivitySkullCollectionDefinition { get; set; }
        public string DestinyActivitySkullSubcategoryDefinition { get; set; }
        public string DestinyBondDefinition { get; set; }
        public string DestinyCharacterCustomizationCategoryDefinition { get; set; }
        public string DestinyCharacterCustomizationOptionDefinition { get; set; }
        public string DestinyCollectibleDefinition { get; set; }
        public string DestinyDestinationDefinition { get; set; }
        public string DestinyEntitlementOfferDefinition { get; set; }
        public string DestinyEquipableItemSetDefinition { get; set; }
        public string DestinyEquipmentSlotDefinition { get; set; }
        public string DestinyEventCardDefinition { get; set; }
        public string DestinyFireteamFinderActivityGraphDefinition { get; set; }
        public string DestinyFireteamFinderActivitySetDefinition { get; set; }
        public string DestinyFireteamFinderLabelDefinition { get; set; }
        public string DestinyFireteamFinderLabelGroupDefinition { get; set; }
        public string DestinyFireteamFinderOptionDefinition { get; set; }
        public string DestinyFireteamFinderOptionGroupDefinition { get; set; }
        public string DestinyStatDefinition { get; set; }
        public string DestinyInventoryItemDefinition { get; set; }
        public string DestinyInventoryItemLiteDefinition { get; set; }
        public string DestinyItemFilterDefinition { get; set; }
        public string DestinyItemTierTypeDefinition { get; set; }
        public string DestinyLoadoutColorDefinition { get; set; }
        public string DestinyLoadoutIconDefinition { get; set; }
        public string DestinyLoadoutNameDefinition { get; set; }
        public string DestinyLocationDefinition { get; set; }
        public string DestinyLoreDefinition { get; set; }
        public string DestinyMaterialRequirementSetDefinition { get; set; }
        public string DestinyMetricDefinition { get; set; }
        public string DestinyObjectiveDefinition { get; set; }
        public string DestinySandboxPerkDefinition { get; set; }
        public string DestinyPlatformBucketMappingDefinition { get; set; }
        public string DestinyPlugSetDefinition { get; set; }
        public string DestinyPowerCapDefinition { get; set; }
        public string DestinyPresentationNodeDefinition { get; set; }
        public string DestinyProgressionDefinition { get; set; }
        public string DestinyProgressionLevelRequirementDefinition { get; set; }
        public string DestinyRecordDefinition { get; set; }
        public string DestinyRewardAdjusterPointerDefinition { get; set; }
        public string DestinyRewardAdjusterProgressionMapDefinition { get; set; }
        public string DestinyRewardItemListDefinition { get; set; }
        public string DestinySackRewardItemListDefinition { get; set; }
        public string DestinySandboxPatternDefinition { get; set; }
        public string DestinySeasonDefinition { get; set; }
        public string DestinySeasonPassDefinition { get; set; }
        public string DestinySocialCommendationDefinition { get; set; }
        public string DestinySocketCategoryDefinition { get; set; }
        public string DestinySocketTypeDefinition { get; set; }
        public string DestinyTraitDefinition { get; set; }
        public string DestinyUnlockCountMappingDefinition { get; set; }
        public string DestinyUnlockEventDefinition { get; set; }
        public string DestinyUnlockExpressionMappingDefinition { get; set; }
        public string DestinyVendorDefinition { get; set; }
        public string DestinyMilestoneDefinition { get; set; }
        public string DestinyActivityModifierDefinition { get; set; }
        public string DestinyReportReasonCategoryDefinition { get; set; }
        public string DestinyArtifactDefinition { get; set; }
        public string DestinyBreakerTypeDefinition { get; set; }
        public string DestinyChecklistDefinition { get; set; }
        public string DestinyEnergyTypeDefinition { get; set; }
        public string DestinySocialCommendationNodeDefinition { get; set; }
        public string DestinyGuardianRankDefinition { get; set; }
        public string DestinyGuardianRankConstantsDefinition { get; set; }
        public string DestinyLoadoutConstantsDefinition { get; set; }
        public string DestinyFireteamFinderConstantsDefinition { get; set; }
        public string DestinyGlobalConstantsDefinition { get; set; }
        public string DestinyInventoryItemConstantsDefinition { get; set; }
    }

    public class Ko
    {
        public string DestinyArtDyeChannelDefinition { get; set; }
        public string DestinyArtDyeReferenceDefinition { get; set; }
        public string DestinyPlaceDefinition { get; set; }
        public string DestinyActivityDefinition { get; set; }
        public string DestinyActivityTypeDefinition { get; set; }
        public string DestinyClassDefinition { get; set; }
        public string DestinyGenderDefinition { get; set; }
        public string DestinyInventoryBucketDefinition { get; set; }
        public string DestinyRaceDefinition { get; set; }
        public string DestinyUnlockDefinition { get; set; }
        public string DestinyStatGroupDefinition { get; set; }
        public string DestinyProgressionMappingDefinition { get; set; }
        public string DestinyFactionDefinition { get; set; }
        public string DestinyVendorGroupDefinition { get; set; }
        public string DestinyRewardSourceDefinition { get; set; }
        public string DestinyUnlockValueDefinition { get; set; }
        public string DestinyRewardMappingDefinition { get; set; }
        public string DestinyItemCategoryDefinition { get; set; }
        public string DestinyDamageTypeDefinition { get; set; }
        public string DestinyActivityModeDefinition { get; set; }
        public string DestinyMedalTierDefinition { get; set; }
        public string DestinyAchievementDefinition { get; set; }
        public string DestinyActivityDifficultyTierCollectionDefinition { get; set; }
        public string DestinyActivityFamilyDefinition { get; set; }
        public string DestinyActivityGraphDefinition { get; set; }
        public string DestinyActivityInteractableDefinition { get; set; }
        public string DestinyActivityLoadoutRestrictionDefinition { get; set; }
        public string DestinyActivitySelectableSkullCollectionDefinition { get; set; }
        public string DestinyActivitySelectableSkullExclusionGroupDefinition { get; set; }
        public string DestinyActivitySkullCategoryDefinition { get; set; }
        public string DestinyActivitySkullCollectionDefinition { get; set; }
        public string DestinyActivitySkullSubcategoryDefinition { get; set; }
        public string DestinyBondDefinition { get; set; }
        public string DestinyCharacterCustomizationCategoryDefinition { get; set; }
        public string DestinyCharacterCustomizationOptionDefinition { get; set; }
        public string DestinyCollectibleDefinition { get; set; }
        public string DestinyDestinationDefinition { get; set; }
        public string DestinyEntitlementOfferDefinition { get; set; }
        public string DestinyEquipableItemSetDefinition { get; set; }
        public string DestinyEquipmentSlotDefinition { get; set; }
        public string DestinyEventCardDefinition { get; set; }
        public string DestinyFireteamFinderActivityGraphDefinition { get; set; }
        public string DestinyFireteamFinderActivitySetDefinition { get; set; }
        public string DestinyFireteamFinderLabelDefinition { get; set; }
        public string DestinyFireteamFinderLabelGroupDefinition { get; set; }
        public string DestinyFireteamFinderOptionDefinition { get; set; }
        public string DestinyFireteamFinderOptionGroupDefinition { get; set; }
        public string DestinyStatDefinition { get; set; }
        public string DestinyInventoryItemDefinition { get; set; }
        public string DestinyInventoryItemLiteDefinition { get; set; }
        public string DestinyItemFilterDefinition { get; set; }
        public string DestinyItemTierTypeDefinition { get; set; }
        public string DestinyLoadoutColorDefinition { get; set; }
        public string DestinyLoadoutIconDefinition { get; set; }
        public string DestinyLoadoutNameDefinition { get; set; }
        public string DestinyLocationDefinition { get; set; }
        public string DestinyLoreDefinition { get; set; }
        public string DestinyMaterialRequirementSetDefinition { get; set; }
        public string DestinyMetricDefinition { get; set; }
        public string DestinyObjectiveDefinition { get; set; }
        public string DestinySandboxPerkDefinition { get; set; }
        public string DestinyPlatformBucketMappingDefinition { get; set; }
        public string DestinyPlugSetDefinition { get; set; }
        public string DestinyPowerCapDefinition { get; set; }
        public string DestinyPresentationNodeDefinition { get; set; }
        public string DestinyProgressionDefinition { get; set; }
        public string DestinyProgressionLevelRequirementDefinition { get; set; }
        public string DestinyRecordDefinition { get; set; }
        public string DestinyRewardAdjusterPointerDefinition { get; set; }
        public string DestinyRewardAdjusterProgressionMapDefinition { get; set; }
        public string DestinyRewardItemListDefinition { get; set; }
        public string DestinySackRewardItemListDefinition { get; set; }
        public string DestinySandboxPatternDefinition { get; set; }
        public string DestinySeasonDefinition { get; set; }
        public string DestinySeasonPassDefinition { get; set; }
        public string DestinySocialCommendationDefinition { get; set; }
        public string DestinySocketCategoryDefinition { get; set; }
        public string DestinySocketTypeDefinition { get; set; }
        public string DestinyTraitDefinition { get; set; }
        public string DestinyUnlockCountMappingDefinition { get; set; }
        public string DestinyUnlockEventDefinition { get; set; }
        public string DestinyUnlockExpressionMappingDefinition { get; set; }
        public string DestinyVendorDefinition { get; set; }
        public string DestinyMilestoneDefinition { get; set; }
        public string DestinyActivityModifierDefinition { get; set; }
        public string DestinyReportReasonCategoryDefinition { get; set; }
        public string DestinyArtifactDefinition { get; set; }
        public string DestinyBreakerTypeDefinition { get; set; }
        public string DestinyChecklistDefinition { get; set; }
        public string DestinyEnergyTypeDefinition { get; set; }
        public string DestinySocialCommendationNodeDefinition { get; set; }
        public string DestinyGuardianRankDefinition { get; set; }
        public string DestinyGuardianRankConstantsDefinition { get; set; }
        public string DestinyLoadoutConstantsDefinition { get; set; }
        public string DestinyFireteamFinderConstantsDefinition { get; set; }
        public string DestinyGlobalConstantsDefinition { get; set; }
        public string DestinyInventoryItemConstantsDefinition { get; set; }
    }

    public class ZhCht
    {
        public string DestinyArtDyeChannelDefinition { get; set; }
        public string DestinyArtDyeReferenceDefinition { get; set; }
        public string DestinyPlaceDefinition { get; set; }
        public string DestinyActivityDefinition { get; set; }
        public string DestinyActivityTypeDefinition { get; set; }
        public string DestinyClassDefinition { get; set; }
        public string DestinyGenderDefinition { get; set; }
        public string DestinyInventoryBucketDefinition { get; set; }
        public string DestinyRaceDefinition { get; set; }
        public string DestinyUnlockDefinition { get; set; }
        public string DestinyStatGroupDefinition { get; set; }
        public string DestinyProgressionMappingDefinition { get; set; }
        public string DestinyFactionDefinition { get; set; }
        public string DestinyVendorGroupDefinition { get; set; }
        public string DestinyRewardSourceDefinition { get; set; }
        public string DestinyUnlockValueDefinition { get; set; }
        public string DestinyRewardMappingDefinition { get; set; }
        public string DestinyItemCategoryDefinition { get; set; }
        public string DestinyDamageTypeDefinition { get; set; }
        public string DestinyActivityModeDefinition { get; set; }
        public string DestinyMedalTierDefinition { get; set; }
        public string DestinyAchievementDefinition { get; set; }
        public string DestinyActivityDifficultyTierCollectionDefinition { get; set; }
        public string DestinyActivityFamilyDefinition { get; set; }
        public string DestinyActivityGraphDefinition { get; set; }
        public string DestinyActivityInteractableDefinition { get; set; }
        public string DestinyActivityLoadoutRestrictionDefinition { get; set; }
        public string DestinyActivitySelectableSkullCollectionDefinition { get; set; }
        public string DestinyActivitySelectableSkullExclusionGroupDefinition { get; set; }
        public string DestinyActivitySkullCategoryDefinition { get; set; }
        public string DestinyActivitySkullCollectionDefinition { get; set; }
        public string DestinyActivitySkullSubcategoryDefinition { get; set; }
        public string DestinyBondDefinition { get; set; }
        public string DestinyCharacterCustomizationCategoryDefinition { get; set; }
        public string DestinyCharacterCustomizationOptionDefinition { get; set; }
        public string DestinyCollectibleDefinition { get; set; }
        public string DestinyDestinationDefinition { get; set; }
        public string DestinyEntitlementOfferDefinition { get; set; }
        public string DestinyEquipableItemSetDefinition { get; set; }
        public string DestinyEquipmentSlotDefinition { get; set; }
        public string DestinyEventCardDefinition { get; set; }
        public string DestinyFireteamFinderActivityGraphDefinition { get; set; }
        public string DestinyFireteamFinderActivitySetDefinition { get; set; }
        public string DestinyFireteamFinderLabelDefinition { get; set; }
        public string DestinyFireteamFinderLabelGroupDefinition { get; set; }
        public string DestinyFireteamFinderOptionDefinition { get; set; }
        public string DestinyFireteamFinderOptionGroupDefinition { get; set; }
        public string DestinyStatDefinition { get; set; }
        public string DestinyInventoryItemDefinition { get; set; }
        public string DestinyInventoryItemLiteDefinition { get; set; }
        public string DestinyItemFilterDefinition { get; set; }
        public string DestinyItemTierTypeDefinition { get; set; }
        public string DestinyLoadoutColorDefinition { get; set; }
        public string DestinyLoadoutIconDefinition { get; set; }
        public string DestinyLoadoutNameDefinition { get; set; }
        public string DestinyLocationDefinition { get; set; }
        public string DestinyLoreDefinition { get; set; }
        public string DestinyMaterialRequirementSetDefinition { get; set; }
        public string DestinyMetricDefinition { get; set; }
        public string DestinyObjectiveDefinition { get; set; }
        public string DestinySandboxPerkDefinition { get; set; }
        public string DestinyPlatformBucketMappingDefinition { get; set; }
        public string DestinyPlugSetDefinition { get; set; }
        public string DestinyPowerCapDefinition { get; set; }
        public string DestinyPresentationNodeDefinition { get; set; }
        public string DestinyProgressionDefinition { get; set; }
        public string DestinyProgressionLevelRequirementDefinition { get; set; }
        public string DestinyRecordDefinition { get; set; }
        public string DestinyRewardAdjusterPointerDefinition { get; set; }
        public string DestinyRewardAdjusterProgressionMapDefinition { get; set; }
        public string DestinyRewardItemListDefinition { get; set; }
        public string DestinySackRewardItemListDefinition { get; set; }
        public string DestinySandboxPatternDefinition { get; set; }
        public string DestinySeasonDefinition { get; set; }
        public string DestinySeasonPassDefinition { get; set; }
        public string DestinySocialCommendationDefinition { get; set; }
        public string DestinySocketCategoryDefinition { get; set; }
        public string DestinySocketTypeDefinition { get; set; }
        public string DestinyTraitDefinition { get; set; }
        public string DestinyUnlockCountMappingDefinition { get; set; }
        public string DestinyUnlockEventDefinition { get; set; }
        public string DestinyUnlockExpressionMappingDefinition { get; set; }
        public string DestinyVendorDefinition { get; set; }
        public string DestinyMilestoneDefinition { get; set; }
        public string DestinyActivityModifierDefinition { get; set; }
        public string DestinyReportReasonCategoryDefinition { get; set; }
        public string DestinyArtifactDefinition { get; set; }
        public string DestinyBreakerTypeDefinition { get; set; }
        public string DestinyChecklistDefinition { get; set; }
        public string DestinyEnergyTypeDefinition { get; set; }
        public string DestinySocialCommendationNodeDefinition { get; set; }
        public string DestinyGuardianRankDefinition { get; set; }
        public string DestinyGuardianRankConstantsDefinition { get; set; }
        public string DestinyLoadoutConstantsDefinition { get; set; }
        public string DestinyFireteamFinderConstantsDefinition { get; set; }
        public string DestinyGlobalConstantsDefinition { get; set; }
        public string DestinyInventoryItemConstantsDefinition { get; set; }
    }

    public class ZhChs
    {
        public string DestinyArtDyeChannelDefinition { get; set; }
        public string DestinyArtDyeReferenceDefinition { get; set; }
        public string DestinyPlaceDefinition { get; set; }
        public string DestinyActivityDefinition { get; set; }
        public string DestinyActivityTypeDefinition { get; set; }
        public string DestinyClassDefinition { get; set; }
        public string DestinyGenderDefinition { get; set; }
        public string DestinyInventoryBucketDefinition { get; set; }
        public string DestinyRaceDefinition { get; set; }
        public string DestinyUnlockDefinition { get; set; }
        public string DestinyStatGroupDefinition { get; set; }
        public string DestinyProgressionMappingDefinition { get; set; }
        public string DestinyFactionDefinition { get; set; }
        public string DestinyVendorGroupDefinition { get; set; }
        public string DestinyRewardSourceDefinition { get; set; }
        public string DestinyUnlockValueDefinition { get; set; }
        public string DestinyRewardMappingDefinition { get; set; }
        public string DestinyItemCategoryDefinition { get; set; }
        public string DestinyDamageTypeDefinition { get; set; }
        public string DestinyActivityModeDefinition { get; set; }
        public string DestinyMedalTierDefinition { get; set; }
        public string DestinyAchievementDefinition { get; set; }
        public string DestinyActivityDifficultyTierCollectionDefinition { get; set; }
        public string DestinyActivityFamilyDefinition { get; set; }
        public string DestinyActivityGraphDefinition { get; set; }
        public string DestinyActivityInteractableDefinition { get; set; }
        public string DestinyActivityLoadoutRestrictionDefinition { get; set; }
        public string DestinyActivitySelectableSkullCollectionDefinition { get; set; }
        public string DestinyActivitySelectableSkullExclusionGroupDefinition { get; set; }
        public string DestinyActivitySkullCategoryDefinition { get; set; }
        public string DestinyActivitySkullCollectionDefinition { get; set; }
        public string DestinyActivitySkullSubcategoryDefinition { get; set; }
        public string DestinyBondDefinition { get; set; }
        public string DestinyCharacterCustomizationCategoryDefinition { get; set; }
        public string DestinyCharacterCustomizationOptionDefinition { get; set; }
        public string DestinyCollectibleDefinition { get; set; }
        public string DestinyDestinationDefinition { get; set; }
        public string DestinyEntitlementOfferDefinition { get; set; }
        public string DestinyEquipableItemSetDefinition { get; set; }
        public string DestinyEquipmentSlotDefinition { get; set; }
        public string DestinyEventCardDefinition { get; set; }
        public string DestinyFireteamFinderActivityGraphDefinition { get; set; }
        public string DestinyFireteamFinderActivitySetDefinition { get; set; }
        public string DestinyFireteamFinderLabelDefinition { get; set; }
        public string DestinyFireteamFinderLabelGroupDefinition { get; set; }
        public string DestinyFireteamFinderOptionDefinition { get; set; }
        public string DestinyFireteamFinderOptionGroupDefinition { get; set; }
        public string DestinyStatDefinition { get; set; }
        public string DestinyInventoryItemDefinition { get; set; }
        public string DestinyInventoryItemLiteDefinition { get; set; }
        public string DestinyItemFilterDefinition { get; set; }
        public string DestinyItemTierTypeDefinition { get; set; }
        public string DestinyLoadoutColorDefinition { get; set; }
        public string DestinyLoadoutIconDefinition { get; set; }
        public string DestinyLoadoutNameDefinition { get; set; }
        public string DestinyLocationDefinition { get; set; }
        public string DestinyLoreDefinition { get; set; }
        public string DestinyMaterialRequirementSetDefinition { get; set; }
        public string DestinyMetricDefinition { get; set; }
        public string DestinyObjectiveDefinition { get; set; }
        public string DestinySandboxPerkDefinition { get; set; }
        public string DestinyPlatformBucketMappingDefinition { get; set; }
        public string DestinyPlugSetDefinition { get; set; }
        public string DestinyPowerCapDefinition { get; set; }
        public string DestinyPresentationNodeDefinition { get; set; }
        public string DestinyProgressionDefinition { get; set; }
        public string DestinyProgressionLevelRequirementDefinition { get; set; }
        public string DestinyRecordDefinition { get; set; }
        public string DestinyRewardAdjusterPointerDefinition { get; set; }
        public string DestinyRewardAdjusterProgressionMapDefinition { get; set; }
        public string DestinyRewardItemListDefinition { get; set; }
        public string DestinySackRewardItemListDefinition { get; set; }
        public string DestinySandboxPatternDefinition { get; set; }
        public string DestinySeasonDefinition { get; set; }
        public string DestinySeasonPassDefinition { get; set; }
        public string DestinySocialCommendationDefinition { get; set; }
        public string DestinySocketCategoryDefinition { get; set; }
        public string DestinySocketTypeDefinition { get; set; }
        public string DestinyTraitDefinition { get; set; }
        public string DestinyUnlockCountMappingDefinition { get; set; }
        public string DestinyUnlockEventDefinition { get; set; }
        public string DestinyUnlockExpressionMappingDefinition { get; set; }
        public string DestinyVendorDefinition { get; set; }
        public string DestinyMilestoneDefinition { get; set; }
        public string DestinyActivityModifierDefinition { get; set; }
        public string DestinyReportReasonCategoryDefinition { get; set; }
        public string DestinyArtifactDefinition { get; set; }
        public string DestinyBreakerTypeDefinition { get; set; }
        public string DestinyChecklistDefinition { get; set; }
        public string DestinyEnergyTypeDefinition { get; set; }
        public string DestinySocialCommendationNodeDefinition { get; set; }
        public string DestinyGuardianRankDefinition { get; set; }
        public string DestinyGuardianRankConstantsDefinition { get; set; }
        public string DestinyLoadoutConstantsDefinition { get; set; }
        public string DestinyFireteamFinderConstantsDefinition { get; set; }
        public string DestinyGlobalConstantsDefinition { get; set; }
        public string DestinyInventoryItemConstantsDefinition { get; set; }
    }

    public class Mobilegearcdn
    {
        public string Geometry { get; set; }
        public string Texture { get; set; }
        public string PlateRegion { get; set; }
        public string Gear { get; set; }
        public string Shader { get; set; }
    }

    public class Mobilegearassetdatabas
    {
        public int version { get; set; }
        public string path { get; set; }
    }

    public class Messagedata
    {
    }

}
