name: publish
on:  
  push:
    branches:
      - master

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
      - run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}
      - name: Publish NuGet package
        run: |
            VERSION=$(git describe --tags --abbrev=0 | sed 's/^v//')
            dotnet pack --configuration Release --output ${{ env.NuGetDirectory }} /p:MinVerVersionOverride=$VERSION